### ISSUE TITLE
标题好像不支持搜索框呀！

### ISSUE THREAD

**Issue by douya40** [bingoogolapple/BGATitlebar-Android#11]
标题好像不支持搜索框呀！

**Comment by bingoogolapple** [comment]
BGATitleBar 就是一个 RelativeLayout，你可以在其内部包裹一个 EditText，这样还更方便自定义 EditText 的样式和位置

**Comment by bingoogolapple** [comment]
![image](https://cloud.githubusercontent.com/assets/8949716/20507368/408d1ba2-b095-11e6-918d-1aa389a0db4b.png)
