### ISSUE TITLE
titlebar左右两边可能会有红点的提示

### ISSUE THREAD

**Issue by cccfly-bake** [bingoogolapple/BGATitlebar-Android#16]
这样的话该如何去添加,看到您里面用的都是V7包中的控件,有点懵,.

**Comment by bingoogolapple** [comment]
BGATitleBar 是继承 RelativeLayout 的，所以你可以把它当成 RelativeLayout 用，在 BGATitleBar 里包裹一个红点控件就可以了

**Comment by cccfly-bake** [comment]
好的.了解了.那我这边就关闭lssues了.谢谢.
